### PR TITLE
Added social cards.

### PR DESCRIPTION
**Pull request by AlexGipp**

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/MahApps/MahApps.Metro.IconPacks?pullRequest=226) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/MahApps/MahApps.Metro.IconPacks?pullRequest=226) before we can accept your contribution.<br/><br/>:x: AlexGipp [sign now](https://cla.dotnetfoundation.org/MahApps/MahApps.Metro.IconPacks?pullRequest=226)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/MahApps/MahApps.Metro.IconPacks?pullRequest=226) it.</sub>

**Comment by timunie** [comment]
Link to the original issue: #225

**Comment by AlexGipp** [comment]
@timunie do i need to do anything else or is this done?

**Comment by punker76** [comment]
@AlexGipp Thank you! These cards are all awesome! So I will start her the vote for my 4 favorites:

Vote with 👍  for 1



with 😄 for 2



with 🎉 for 3



and with ❤️ for 4



My favorites are 1 and 2

**Comment by AlexGipp** [comment]
If you have any suggestions, feel free to let me know.

**Comment by punker76** [comment]
> If you have any suggestions, feel free to let me know.

@AlexGipp I have a little one, the "Awesome icon packs for WPF and UWP in one library" could be maybe more generic, like "Awesome icon packs for your applications in one library", because one plan is to make a version for [Avalonia](https://avaloniaui.net/) too.

**Comment by timunie** [comment]
> If you have any suggestions, feel free to let me know.

I don't know which tool you used for your cards, But if possible it would be nice if you also share the raw data with the community, e.g. as `svg`. 

By the way: I am impressed by all of your cards in such a short time :-)

**Comment by AlexGipp** [comment]
@timunie i used photoshop, i will make sure to add the psd files in the next push.

**Comment by AlexGipp** [comment]
Hey guys, just added another card and the psd files. (also update the text @punker76 )

**Comment by batzen** [comment]
1 is missing a "." after MahApps, or was that intentional?

**Comment by AlexGipp** [comment]
@batzen yeah i forgot that one, added it though

**Comment by punker76** [comment]
@AlexGipp your changes have been merged, thanks for your contribution 👍 Thank you for this nice work!

**Comment by AlexGipp** [comment]
No problem, do you have any simple programming issues i could work on?

**Pull request merged**
