### PR TITLE
Improve IconPacks Browser with new features

### LINKED ISSUE #12: Tiny simple editor
Add a tiny simple editor to change size, background and foreground and copy the result as Xaml into the clipboard...

### LINKED ISSUE #57: Export Icon as Image From IconPacks Browser
It would be awesome if we could export icons as images like in Syncfusion Metro Studio.
https://youtu.be/eWAemchE6Sg?t=1m4s

### LINKED ISSUE #230: Idea for some improvements of the IconPack-Browser
**Is your feature request related to a problem? Please describe.**
IMO the current implementation of the IconPacksBrowser is great, but has some limitations:
- The more IconPacks are added the more space is needed by the TabHeader. Searching for a specific IconPack gets "harder"
- The "All"-tab does not optically separate form the other tabs
- There is not much space left for new features, such as
   - Displaying the Hyperlink #228 
   - Add more Export options #57 #12 

**Describe the solution you'd like**
Maybe using a `HamburgerMenu` instead of `TabControl` needs less space and the `All`-Items can be shown after a `Separator`. The new free space can be used to have an advanced Preview Pane with additional export options, such as
- Selecting a `Color`
- Setting the `Size`
- Export the icon e.g. as `*.png, *.bmp, *.ico` and `*.svg`
- Optional: Create a Settings-Page

**Describe alternatives you've considered**
Leave it as it is now

**Additional context**
I have an idea in my mind and will show it soon. If the idea is accepted, it can be adjusted in detail

### PR DESCRIPTION
**Pull request by timunie**
## What changed?
This is a proposal for a different IconPacksBrowser. For now not all Features are implemented as it is more meant as a proposal at this moment. Currently this changed:
- Use `HamburgerMenu` instead of `TabControl`
- Use a `PreviewPane` to display, adjust and (later) export the selected Icon
- More space for Icons if needed
- DataTemplate is now more "generic". This should lead to less effort if there are more `IconPacks` added

## Screenshots
HamburgerMenuProposal

## Closed Issues

Closes #230 
Closes #57 
Closes #12 
Closes #51

### CODE REVIEW

**Comment by punker76** [comment]
@timunie appveyor shows this error
```
C:\projects\mahapps-metro-iconpacks\src\MahApps.Metro.IconPacks.Browser\MainWindow.xaml(338,11): error MC3000: 'The 'Canvas' start tag on line 315 position 18 does not match the end tag of 'DataTemplate'. Line 338, position 11.' XML is not valid.
```

**Comment by timunie** [comment]
It did work and compile, but now the `XAML` of the MainWindow is totally rubbish. I have no idea what happend here. But if you are interested in this, I'll double-check. If you want to stick with the current design we can also close this PR. 

@punker76 please give me a short :+1: or :-1: . :pray:

**Comment by punker76** [comment]
Here some thoughts (suggestions):

- "Filter by" should be always visible, maybe on the right top on the title header of the showing icon page
- Save as Svg could be difficult, because some paths are inverted (and not the original one)

**Comment by timunie** [comment]
Hi @punker76 

Thank you for the suggestions. The issue was caused by the last rebase, I'll fix this when I have some time for it. Moving the searchtextbox to the right was also something I was thinking about. 

> Save as Svg could be difficult, because some paths are inverted (and not the original one)

:thinking: Let's see if there is a way or not. Do you have an example which icon is inverted? I would like to use this for testing

Info: I would like to use the `ColorPicker` https://github.com/MahApps/MahApps.Metro/pull/3930 to let the user select the colors. So I would also like to wait for this before you merge this PR.

Nevertheless I can make smaller PR for useful features. Especially the `DataTemplateSelector` seems to be very handy. Should I make a separate PR for this?

Happy coding 
Tim

**Comment by Insire** [comment]
> Do you have an example which icon is inverted?
iirc the fontawesome icons are inverted

**Comment by timunie** [comment]
@punker76 do you mean the following image by 

> Save as Svg could be difficult, because some paths are inverted (and not the original one)

image

If yes, I think I know how to export the data in the right direction. We "just" have to translate the `LayoutTransform`-Matrix to `svg`.

**Comment by timunie** [comment]
> @punker76 do you mean the following image by
> 
> > Save as Svg could be difficult, because some paths are inverted (and not the original one)
> 
> image
> 
> If yes, I think I know how to export the data in the right direction. We "just" have to translate the `LayoutTransform`-Matrix to `svg`.

Here are some exported examples: 
[Example-Export.zip](https://github.com/MahApps/MahApps.Metro.IconPacks/files/5510724/Example-Export.zip)

**Comment by timunie** [comment]
Hi @punker76, 

should we offer support for custom `ExportTemplates` and `CopyToClipboardTemplates`? That way the user could modify the template and for example copy the icon with `Width`, `Height` or `Foreground` set. 

Happy coding and a nice weekend
Tim

**Comment by timunie** [comment]
Hi @punker76 ,

I think I am good to go. Functions which are now implemented are:
- other design
- search via `[Ctrl]+[F]`
- configure preview size and color
- Export icon to `svg`, `xaml` and image
- Display more icon information
- Support for theming
- Support for custom Export and CopyToClipboard-Templates. 

image

I which everyone happy coding, happy x-mas 🎄 and a happy new year 🎆
Tim

**Comment by punker76** [comment]
finally

image

**Comment by punker76** [comment]
@timunie your changes have been merged, thanks for your contribution 👍

**Pull request merged**
