### PR TITLE
Added ability to copy geometry data directly from browser interface.

### PR DESCRIPTION
**Pull request by BlackGad**
Ability to copy geometry data directly from browser interface.

### CODE REVIEW

**Comment by punker76** [comment]
@BlackGad your changes have been merged, thanks for your contribution 👍

**Comment by GF-Huang** [comment]
Any example to use geometry data in WPF such like this?

`M 5.5,20C 2.46243,20 0,17.5376 0,14.5C 0,11.463 2.46144,9.00099 5.49816,9C 6.47772,6.65105 8.79605,5 11.5,5C 14.9316,5 17.7421,7.6592 17.9832,11.0294L 18.5,11C 20.9853,11 23,13.0147 23,15.5C 23,17.9853 20.9853,20 18.5,20L 5.5,20 Z M 5.5,10C 3.01472,10 0.999999,12.0147 0.999999,14.5C 0.999999,16.9853 3.01472,19 5.5,19C 7.22096,19 16.6464,19 18.5,19C 20.433,19 22,17.433 22,15.5C 22,13.567 20.433,12 18.5,12C 17.9361,12 17.4033,12.1334 16.9315,12.3703C 16.9766,12.0868 17,11.7961 17,11.5C 17,8.46244 14.5376,6 11.5,6C 8.96324,6 6.8276,7.7174 6.19235,10.0529L 5.5,10 Z `

**Comment by punker76** [comment]
@GF-Huang Simple sample:

```xaml
<Path Fill="Red" Data="M 5.5,20C 2.46243,20 0,17.5376 0,14.5C 0,11.463 2.46144,9.00099 5.49816,9C 6.47772,6.65105 8.79605,5 11.5,5C 14.9316,5 17.7421,7.6592 17.9832,11.0294L 18.5,11C 20.9853,11 23,13.0147 23,15.5C 23,17.9853 20.9853,20 18.5,20L 5.5,20 Z M 5.5,10C 3.01472,10 0.999999,12.0147 0.999999,14.5C 0.999999,16.9853 3.01472,19 5.5,19C 7.22096,19 16.6464,19 18.5,19C 20.433,19 22,17.433 22,15.5C 22,13.567 20.433,12 18.5,12C 17.9361,12 17.4033,12.1334 16.9315,12.3703C 16.9766,12.0868 17,11.7961 17,11.5C 17,8.46244 14.5376,6 11.5,6C 8.96324,6 6.8276,7.7174 6.19235,10.0529L 5.5,10 Z" />
```

**Comment by GF-Huang** [comment]
BTW, how can I set the iconPacks markup whether fill or only outline? 

For example: `{iconPacks:BootstrapIcons Kind=Cloud}`

image

How can I make it looks like this 
image

**Comment by BlackGad** [comment]
You can't :) use another set of icons instead. Or manually modify [geometry](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/graphics-multimedia/path-markup-syntax?view=netframeworkdesktop-4.8).

**Pull request merged**
