### PR TITLE
Add PackIconKind image converter (WPF)

### PR DESCRIPTION
**Pull request by punker76**
- Add new `PackIconKindToImageConverter`
The `PackIconKindToImageConverter` converts a PackIcon kind to a DrawingImage which can be used with an ImageSource.
- Add Image converter for all separate projects
  + `PackIconBoxIconsKindToImageConverter`
  + `PackIconEntypoKindToImageConverter`
  + `PackIconEvaIconsKindToImageConverter`
  + `PackIconFeatherIconsKindToImageConverter`
  + `PackIconFontAwesomeKindToImageConverter`
  + `PackIconIoniconsKindToImageConverter`
  + `PackIconJamIconsKindToImageConverter`
  + `PackIconMaterialDesignKindToImageConverter`
  + `PackIconMaterialKindToImageConverter`
  + `PackIconMaterialLightKindToImageConverter`
  + `PackIconMicronsKindToImageConverter`
  + `PackIconModernKindToImageConverter`
  + `PackIconOcticonsKindToImageConverter`
  + `PackIconPicolIconsKindToImageConverter`
  + `PackIconRPGAwesomeKindToImageConverter`
  + `PackIconSimpleIconsKindToImageConverter`
  + `PackIconTypiconsKindToImageConverter`
  + `PackIconUniconsKindToImageConverter`
  + `PackIconWeatherIconsKindToImageConverter`
  + `PackIconZondiconsKindToImageConverter`
- Add new `PackIconImageExtension`
The `PackIconImageExtension` converts a PackIcon kind to a DrawingImage which can be used with an ImageSource.
- Add Image MarkupExtension for all separate projects
  + `PackIconBoxIconsImageExtension`
  + `PackIconEntypoImageExtension`
  + `PackIconEvaIconsImageExtension`
  + `PackIconFeatherIconsImageExtension`
  + `PackIconFontAwesomeImageExtension`
  + `PackIconIoniconsImageExtension`
  + `PackIconJamIconsImageExtension`
  + `PackIconMaterialDesignImageExtension`
  + `PackIconMaterialImageExtension`
  + `PackIconMaterialLightImageExtension`
  + `PackIconMicronsImageExtension`
  + `PackIconModernImageExtension`
  + `PackIconOcticonsImageExtension`
  + `PackIconPicolIconsImageExtension`
  + `PackIconRPGAwesomeImageExtension`
  + `PackIconSimpleIconsImageExtension`
  + `PackIconTypiconsImageExtension`
  + `PackIconUniconsImageExtension`
  + `PackIconWeatherIconsImageExtension`
  + `PackIconZondiconsImageExtension`

### Converter Sample

```xaml
<Image VerticalAlignment="Center"
       Width="72"
       Height="72"
       Margin="2"
       Source="{Binding KindProperty, Converter={iconPacks:PackIconKindToImageConverter Brush=Black}}" />

<Image VerticalAlignment="Center"
       Width="72"
       Height="72"
       Margin="2"
       Source="{Binding KindProperty, Converter={iconPacks:PackIconBoxIconsKindToImageConverter Brush=Black}}" />
```

### MarkupExtension Sample

```xaml
<Window x:Class="WpfApp.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:iconPacks="http://metro.mahapps.com/winfx/xaml/iconpacks"
        Icon="{iconPacks:FontAwesomeImage FontAwesomeBrands, Brush=Black}">

</Window>        

<Image Width="72" Height="72"
       Margin="2"
       Source="{iconPacks:FontAwesomeImage FontAwesomeBrands, Brush=DodgerBlue}" />
```

Closes #113

### CODE REVIEW

**Comment by Phyxion** [comment]
A bit of feedback. Thickness is missing, this is very useful if you want to draw thinner icons (some icons are too thick in source and when scaled down to small sizes it's becoming hard to read see details).

**Comment by punker76** [comment]
@Phyxion Most of the icons are not Pen (Stroke) based, so IMO this property would be pointless and doesn't work.

**Comment by Phyxion** [comment]
I'm using it only for Material and FontAwesome and that thins/thicks just fine (both up to a certain point of course, too large values for example will create a filled square). Are these both pen-based then?

**Comment by punker76** [comment]
@Phyxion Both are not Pen based. So if you use it with a Pen, then you will get wrong Icons.

2019-12-02_14h08_25

2019-12-02_14h08_37

2019-12-02_14h11_14

**Comment by Phyxion** [comment]
At such large sizes, you'll probably notice that indeed, but for small icons (12x12 or 16x16 for example) some icons look and scale much better with a thinner pen (0.05). At small thickness changes there's no noticable difference in the resulting icon except for being drawn thinner/clearer. Of course if you use 0.0001 or 100 thickness then it'll look terrible as they're not made for such numbers.

I've also noticed that you're using pen thickness of 2. 0.25 gives the best results for the icon packs I've tested (https://github.com/MahApps/MahApps.Metro.IconPacks/issues/39#issuecomment-292509036). 2 is too thick compared to the original icons.

**Comment by goldcode** [comment]
The following windows properties helped to keep the icon
    IconBitmapScalingMode="LowQuality"
    IconEdgeMode="Unspecified"
> ### MarkupExtension Sample
> ```
> <Window x:Class="WpfApp.MainWindow"
>         xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
>         xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
>         xmlns:iconPacks="http://metro.mahapps.com/winfx/xaml/iconpacks"
>         Icon="{iconPacks:FontAwesomeImage FontAwesomeBrands, Brush=Black}">
> 
> </Window>        
> 
> <Image Width="72" Height="72"
>        Margin="2"
>        Source="{iconPacks:FontAwesomeImage FontAwesomeBrands, Brush=DodgerBlue}" />
> ```
> 
> Closes #113

**Comment by nadcraker** [comment]
I'm having trouble setting the Width of the icon using the MarkupExtension syntax. Should it be possible?

**Comment by timunie** [comment]
@nadcraker please ask questions like this here: https://gitter.im/MahApps/MahApps.Metro 

Thank you and happy coding
Tim

**Pull request merged**
