### PR TITLE
Remove delegate allocation

### PR DESCRIPTION
**Pull request by kronic**

### CODE REVIEW

**Comment by punker76** [comment]
@kronic Can you explain the benefit of these changes?

**Comment by kronic** [comment]
@punker76 there will be no allocation for the delegate when called.

**Comment by punker76** [comment]
@kronic I never saw such a suggestion, also if I look to the official [doc](https://docs.microsoft.com/en-us/dotnet/api/system.windows.propertychangedcallback?view=net-5.0). So if you have any information about htis then please show me. Thx

**Comment by kronic** [comment]
@punker76 
https://sharplab.io/#gist:bdaac746f37bcd9bba8436ffeb1e81e4

**Comment by kronic** [comment]
https://devblogs.microsoft.com/dotnet/understanding-the-cost-of-csharp-delegates/

**Comment by batzen** [comment]
@kronic Could you elaborate a bit more on what your changes achieve exactly? The value stored in the static metadata should be the same as before.
Your changes would reduce allocations if the delegate would be created multiple times, but in case of property metadata this is not the case.
As shown in your SharpLab example your changes lead to increased code size and an additional backing field which stores the reference to the delegate. So instead of only storing the delegate instance in the property metadata we now would store it twice, once in the metadata and once in the backing field.

**Pull request closed without merging**
